### ISSUE TITLE
Builds stopped

### ISSUE THREAD

**Issue by scottsweb** [lroguet/rpi-home-assistant#32]
It looks like builds are no longer being created with the latest version of Home Assistant (0.110.x)

**Comment by mattmattmatt** [comment]
Any news or progress on this, @lroguet? I really appreciated the automated Docker builds for the Pi.

**Comment by mattmattmatt** [comment]
For those interested in the latest version (currently `0.111.2`), I created [an image of Home Assistant for Raspberry Pi on Docker Hub](https://hub.docker.com/r/prettygoodguy/rpi-ha/tags). 

I'll try to keep it updated, but since I'm running these builds manually, I may be a few days or even weeks behind now and then.

**Comment by lroguet** [comment]
@scottsweb & @mattmattmatt - Broken Docker installation on the Raspberry Pi following upgrade to Stretch. The builds are catching up now, starting with 0.111.4 and going back.

**Comment by lroguet** [comment]
Should be back to normal.
